theme: jekyll-theme-cayman
title: [Homepage of Hicham Janati]
description: [A glimpse of my work]
keywords: "Hicham, Janati, Inria, Ensae, Optimal transport, neuroscience, machine learning"

home: ./index.html
publications: ./publications.html
teaching: ./teaching.html
